apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
        - name: cloud-gateway-app
          image: dhairya16/cloudgateway:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SERVER_MAX_HTTP_REQUEST_HEADER_SIZE
              value: "65536" # 64KB (double the previous size)
            - name: SPRING_CLOUD_GATEWAY_HTTP_CLIENT_MAX_HEADER_SIZE
              value: "65536"
            - name: SPRING_CLOUD_GATEWAY_HTTP_CLIENT_RESPONSE_TIMEOUT
              value: "60000"

            # Additional critical settings
            - name: SPRING_CLOUD_GATEWAY_ADD_PROXY_HEADERS
              value: "false"
            - name: SPRING_CLOUD_GATEWAY_STRIP_PREFIX
              value: "true"
            - name: SPRING_CLOUD_GATEWAY_FORWARDED_HEADERS_ENABLED
              value: "false"

            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_server_url

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway-app
  ports:
    - port: 80
      targetPort: 9090
