apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
spec:
  selector:
    matchLabels:
      app: payment-service-app
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
        - name: payment-service-app
          image: dhairya16/paymentservice:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_MAX_HTTP_REQUEST_HEADER_SIZE
              value: "65536"
            - name: SERVER_HTTP2_ENABLED
              value: "false"
            - name: SERVER_COMPRESSION_ENABLED
              value: "true"
            - name: SERVER_USE_FORWARD_HEADERS
              value: "false"

            - name: SPRING_APPLICATION_NAME
              value: "PAYMENT-SERVICE"
            - name: SERVER_PORT
              value: "8081"
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_server_url
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: hostname

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service-app
  ports:
    - port: 80
      targetPort: 8081
